# Generated by Django 5.0.14 on 2025-10-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ta",
            name="day",
        ),
        migrations.AddField(
            model_name="ta",
            name="days",
            field=models.CharField(
                blank=True,
                help_text="Example: Mondays, Wednesdays, Fridays",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="ta",
            name="information",
            field=models.TextField(
                blank=True,
                help_text="Optional: Add info about yourself, including classes you'd be comfortable tutoring.",
            ),
        ),
    ]
